# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [4]:
import numpy as np
print (np.__version__)
np.show_config

1.20.1


<function numpy.__config__.show()>

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [11]:
my_list = [1,2,3,4,5]
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4, 5])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [16]:
a=np.zeros((9))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [17]:
b = np.array([1,2,3])
print(b.itemsize)
print(b.size)

4
3


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [18]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [20]:
c=np.zeros(12)
c[6]=1
print(c)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [23]:
a=np.arange(20,59)
print(a)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [24]:
b=np.arange(20,59)
b=b[::-1]
print(b)

[58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35
 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [36]:
c=np.arange(12,21)
c=c.reshape(3,3)
print(c)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [30]:
a=np.nonzero([3,7,0,0,9,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [31]:
b=np.eye(4,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [7]:
c=np.random.random((2,2,2))
print(c)

[[[0.90390505 0.70710712]
  [0.40005434 0.49257489]]

 [[0.10897818 0.75631511]
  [0.96804108 0.35124451]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [9]:
a=np.random.random((9,9))
print(a)
max=np.max(a)
min=np.min(a)
print(max,min)

[[0.53414592 0.44327583 0.85737822 0.791293   0.36153716 0.06584995
  0.57029568 0.11581582 0.46976197]
 [0.56842673 0.05094156 0.14480672 0.96916296 0.54940137 0.08889584
  0.89600217 0.84689971 0.74431429]
 [0.89179027 0.857428   0.20091641 0.30875266 0.95806865 0.64776478
  0.07844288 0.4448968  0.44956711]
 [0.83123413 0.69148189 0.23227609 0.91394918 0.18591256 0.05552284
  0.7648904  0.01346425 0.48632081]
 [0.34768504 0.34332902 0.8987391  0.27414474 0.58548861 0.56824272
  0.43243681 0.56474933 0.07913798]
 [0.75934373 0.29991496 0.916255   0.27144371 0.86835013 0.39521037
  0.86022587 0.37113673 0.43486515]
 [0.43634907 0.14229077 0.98501522 0.53075425 0.00368446 0.43310618
  0.90621951 0.46266528 0.83399863]
 [0.71652892 0.06287125 0.81558506 0.9287995  0.03772011 0.98572376
  0.43605156 0.65517806 0.71705102]
 [0.6615906  0.00375342 0.96937592 0.55793936 0.55136167 0.52854673
  0.14567965 0.63351673 0.42718457]]
0.9857237616481102 0.0036844580521023795


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [10]:
b=np.random.random(20)
print(b)
avg0=np.average(b)
avg1=np.mean(b)
print(avg0,avg1)

[0.36338813 0.43731912 0.06990273 0.02567112 0.03152132 0.69436505
 0.25729455 0.95140927 0.17433662 0.09414804 0.46701886 0.90009268
 0.45290707 0.16513382 0.39093356 0.16345937 0.03314527 0.05390986
 0.46266838 0.31799544]
0.32533101344746423 0.32533101344746423


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [12]:
c=np.ones((5,5))
c[1:-1, 1:-1]=0
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [37]:
b=np.ones((5,5))
b=np.pad(b,pad_width=1,mode='constant',constant_values=0)
print(b)
c[:,[0,-1]]=0
c[[0,-1],:]=0
print(c)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [18]:
nan
False
False
nan
True
False

NameError: name 'nan' is not defined

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [19]:
b=np.diag(1+np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [38]:
c=np.zeros((6,6),dtype=int)
c[1::2,::2]=1
c[::2,1::2]=1
print(c)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [32]:
print(np.unravel_index(99,(8,9,10)))

(1, 0, 9)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [34]:
a=np.array([[0,1],[1,0]])
print(a)
b=np.tile(a,(4,4))
print(b)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [36]:
a=np.random.random((6,6))
print(a)
b=(a-np.mean(a))/np.std(a)
print(b)

[[0.13503103 0.29421746 0.8112145  0.18715641 0.71441145 0.59935436]
 [0.39685734 0.78504944 0.60413277 0.56945068 0.14567184 0.49503856]
 [0.19641922 0.47751018 0.54064077 0.59847086 0.13462546 0.20668068]
 [0.40516596 0.24538697 0.52819372 0.80210117 0.06065917 0.06306878]
 [0.31527665 0.62504998 0.37792505 0.11336401 0.28045171 0.50856888]
 [0.63754011 0.88840395 0.67070608 0.25198465 0.50498195 0.32879332]]
[[-1.28257268 -0.59167673  1.65217773 -1.05633973  1.23203615  0.73266895]
 [-0.14620229  1.53861693  0.75340803  0.60288192 -1.23638978  0.27992075]
 [-1.01613758  0.20384463  0.47784203  0.72883442 -1.28433296 -0.97160113]
 [-0.11014151 -0.80360927  0.42381976  1.61262432 -1.60535914 -1.594901  ]
 [-0.50027628  0.84419227 -0.22837164 -1.37661122 -0.65142239  0.33864462]
 [ 0.89840155  1.98719296  1.04234744 -0.77497423  0.32307675 -0.44161164]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [46]:
print(np.dot(np.random.random((6,3)),np.random.random((3,4))))
print(np.pnes((6,3))*np.ones((3,4)))

[[0.9902888  0.99682469 0.99305937 0.51588614]
 [0.89916814 0.8256432  0.94351196 0.59030825]
 [0.7165023  0.34373051 0.4692712  0.23745889]
 [0.86440777 1.00699852 1.06592284 0.67305818]
 [1.14852234 0.90590536 1.18550468 0.8258238 ]
 [0.97011992 0.86055009 0.86860709 0.41951963]]


AttributeError: module 'numpy' has no attribute 'pnes'

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [53]:
a=np.arange(11)
a[(3<a)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [ ]:
nan
0
[-2.14748365e+09]

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [54]:
a=np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)),a))
print(np.where(a>0,np.ceil(a),np.floor(a)))

[-7.34879329  1.48309528  3.20751474  2.13587831 -6.20725219  2.63208143
  1.7406698  -4.06889904 -4.83198687  8.89451743]
[-8.  2.  4.  3. -7.  3.  2. -5. -5.  9.]
[-8.  2.  4.  3. -7.  3.  2. -5. -5.  9.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [57]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
print(a,b)
print(np.intersect1d(a,b))

[3 5 6 6 3 8 7 4 9 2] [7 4 8 5 7 0 0 5 3 6]
[3 4 5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

SyntaxError: invalid syntax (<ipython-input-59-0c885138dce0>, line 4)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

In [62]:
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


<ipython-input-62-297b4fa8a8eb>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

In [65]:
yesterday=np.datetime64('today')
today=np.datetime64('today')
tomorrow=np.datetime64('today')
print(yesterday,today,tomorrow)

2022-05-01 2022-05-01 2022-05-01


#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

In [67]:
a=np.arange('2016-01','2016-02',dtype='datetime64[D]')
print(a)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [68]:
A=np.ones(3)*1
B=np.ones(3)*2
print(A,B)
np.add(A,B,out=B)
print(A,B)
np.divide(A,2,out=A)
print(A,B)
np.negative(A,out=A)
print(A,B)
np.multiply(A,B,out=A)
print(A,B)

[1. 1. 1.] [2. 2. 2.]
[1. 1. 1.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

In [73]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(a//1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[6. 7. 6. 3. 2. 8. 7. 0. 4. 5.]
[6. 7. 6. 3. 2. 8. 7. 0. 4. 5.]
[6. 7. 6. 3. 2. 8. 7. 0. 4. 5.]
[6 7 6 3 2 8 7 0 4 5]
[6. 7. 6. 3. 2. 8. 7. 0. 4. 5.]


#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

In [75]:
a=np.zeros((3,3))
a+=np.arange(3)
print(a)
a=np.tile(np.arange(0,3),(3,1))
print(a)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

In [79]:
def generate():
    for x in range(9):
        yield x
a=np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

In [82]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

In [86]:
a=np.random.random(10)
print(a)
a=np.sort(a)
print(a)

[0.27028595 0.4261723  0.39498117 0.77493731 0.55611015 0.23296705
 0.32937459 0.04793483 0.61264394 0.73417306]
[0.04793483 0.23296705 0.27028595 0.32937459 0.39498117 0.4261723
 0.55611015 0.61264394 0.73417306 0.77493731]


#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

In [89]:
a=np.arange(10)
np.add.reduce(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

In [92]:
a=np.random.randint(1,3,6)
b=np.random.randint(1,3,6)
equal=np.allclose(a,b)
print(equal)
equal=np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

In [95]:
a=np.zeros(8)
a.flags.writeable=False
a[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

In [99]:
a=np.random.random((5,2))
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.37624783 0.79595811 0.84478826 0.40463045 0.47605805]
[0.86240797 0.61871285 0.7200834  1.55410492 1.00935407]


#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

In [103]:
a=np.random.random(5)
print(a)
a[a.argmax()]=0
print(a)

[3.18694462e-01 8.81453239e-05 7.60303839e-01 2.58151054e-01
 4.19953570e-01]
[3.18694462e-01 8.81453239e-05 0.00000000e+00 2.58151054e-01
 4.19953570e-01]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

In [104]:
a=np.zeros((3,3),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(a)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

In [107]:
a=np.arange(5)
b=a+0.5
c=1/np.subtract.outer(a,b)
print(np.linalg.det(c))

-131.91659501325745


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

In [110]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


<ipython-input-110-09d3fcbaa3b3>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  for dtype in [np.float32,np.float]:


#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

In [112]:
np.set_printoptions(threshold=float("inf"))
a=np.zeros((20,20))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

In [115]:
a=np.arange(22)
b=np.random.uniform(0,22)
index=(np.abs(a-b)).argmin()
print(a[index])

10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

In [129]:
a= np.arange(10, dtype=np.float32)
a= a.astype(np.int32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

In [132]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
a= np.genfromtxt(s, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-132-b12d504a0de6>:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a= np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

In [136]:
b= np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(b):
    print(index, value)
for index in np.ndindex(b.shape):
    print(index, b[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

In [139]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

In [141]:
n=10
p=3
a=np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

In [142]:
a=np.random.rand(3,6)
b=a-a.mean(axis=1, keepdims=True)
b=a-a.mean(axis=1).reshape(-1, 1)
print(b)

[[ 0.10317151 -0.17132135  0.31450876  0.33240527 -0.29963632 -0.27912787]
 [ 0.13482492 -0.04742371  0.23867904  0.17162245 -0.53772379  0.04002108]
 [ 0.1095772  -0.47078861  0.36201379  0.2870932  -0.3717346   0.08383903]]


#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

In [145]:
a= np.random.randint(0,5,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[2 3 1]
 [2 2 2]
 [1 4 0]]
[[2 2 2]
 [2 3 1]
 [1 4 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

In [148]:
a= np.random.randint(0,5,(5,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

In [153]:
a=np.random.uniform(0,2,10)
b=0.5
c=a.flat[np.abs(a-b).argmin()]
print(c)

0.2046812038916015


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

In [154]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

In [167]:
a= np.ones(5)
b= np.random.randint(0,len(a),10)
a+= np.bincount(b, minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

[5. 2. 2. 2. 4.]
[9. 3. 3. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

In [176]:
a=[1,2,3,4,5,6]
b=[1,3,9,3,4,1]
c=np.bincount(a,b)
print(c)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

In [171]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

In [178]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.sum(axis=(-2,-1))
print(sum)
sum=a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 57 65 49]
 [43 53 48 59]
 [34 62 55 48]]
[[58 57 65 49]
 [43 53 48 59]
 [34 62 55 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

In [182]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))
np.sum(a*b.T,axis=1)
np.einsum("ij,ji->i",a,b)

array([1.40965926, 1.76780379, 2.47852886, 1.20860969, 1.09927431])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

In [184]:
a=np.array([1,2,3,4,5])
nz=3
a0=np.zeros(len(a)+(len(a)-1)*(nz))
a0[::nz+1]=a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

In [185]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

In [190]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

In [195]:
faces = np.random.randint(0,100,(10,3))
a=np.roll(faces.repeat(2,axis=1),-1,axis=1)
a=a.reshape(len(a)*3,2)
a=np.sort(a,axis=1)
b=a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b=np.unique(c)
print(c)

[0. 1. 3. 9. 3. 4. 1.]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

In [199]:
a=np.bincount([1,3,5,5,6,7,8])
b=np.repeat(np.arange(len(a)),a)
print(b)

[1 3 5 5 6 7 8]


#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

In [200]:
def moving_average(a, n=4) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
b= np.arange(20)
print(moving_average(b, n=4))

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

In [205]:
Z = np.random.randint(0,2,50)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,50)
np.negative(Z, out=Z)

array([-0.78528757, -0.05837109, -0.07034828,  0.63594646,  0.90586543,
        0.37567399,  0.49344483,  0.14676969,  0.88694673, -0.56536174,
        0.95815369,  0.51329247,  0.10833846,  0.56416309,  0.02445564,
       -0.3182485 ,  0.44625297,  0.85889863,  0.09634238,  0.4899977 ,
       -0.35508264, -0.42296384, -0.14319907, -0.02521061, -0.72454794,
        0.95448894,  0.35581693,  0.80671192, -0.42351279,  0.3513555 ,
       -0.16505611,  0.16260268,  0.3391709 ,  0.47156329, -0.53482266,
        0.17508577,  0.06971314,  0.29320489,  0.6897094 ,  0.17822183,
       -0.20026007,  0.14268413,  0.72801764,  0.84892506, -0.42927886,
       -0.32701273, -0.39338283,  0.5650748 , -0.49650617,  0.13365525])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [211]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[14.23817972  0.7513201   2.32531941  6.59555947  0.40006761 10.29993588
   1.84002836  7.64683376  2.77648213 11.93670712]
 [10.33965046  3.48217968  7.63948291  4.99875172  3.49720095  6.9202279
   8.10051388  6.19441498  1.69547125  7.34206062]
 [13.28376939  0.35285591  4.60463031  6.59460873  1.50695897  9.57080865
   4.22864154  7.70229963  1.56322049 10.66639694]
 [ 8.25636127  5.18292849  2.37165623  0.91372912  2.3172062   4.29981696
   4.35247497  2.01195456  3.10341088  6.09240601]
 [ 1.27315894 12.05499165  1.62290573  6.03928281  5.33727475  2.78539118
   6.58309166  4.90353553  9.87040601  0.61087258]
 [ 4.40524176  9.00671665  2.44905192  2.72529764  3.50513947  0.44169309
   6.01161311  1.59582058  6.89467002  2.32274784]
 [ 0.12634758 13.53000195  6.50203872  5.18727977  0.96106595  3.44651843
  11.32584982  3.937651   11.58743052  2.45554037]
 [ 0.24691394 13.35145435  5.65012163  5.41196526  1.75130582  3.41106029
  10.53066761  4.18160863 11.36587028  2.21120199]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`